# Generated by Django 6.1.1 on 2026-09-17 07:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text='Unique student registration/roll code (e.g., STU-2026-001)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Student ID must be 4-20 uppercase alphanumeric characters or hyphens (e.g., STU-2026-001).', regex='^[A-Z0-9\\-]{4,20}$')])),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(help_text='Unique student email address', max_length=254, unique=True)),
                ('phone', models.CharField(help_text='Contact telephone number', max_length=20)),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Information Technology', 'Information Technology'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Business Administration', 'Business Administration'), ('Data Science', 'Data Science')], max_length=50)),
                ('enrollment_date', models.DateField(help_text='Official date of enrollment')),
                ('gpa', models.DecimalField(decimal_places=2, help_text='Cumulative Grade Point Average between 0.00 and 4.00', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('4.00'))])),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Graduated', 'Graduated'), ('Suspended', 'Suspended')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student_id'], name='students_st_student_e7126a_idx'), models.Index(fields=['email'], name='students_st_email_e271bc_idx'), models.Index(fields=['department'], name='students_st_departm_c67345_idx'), models.Index(fields=['status'], name='students_st_status_5e2210_idx')],
            },
        ),
    ]
